# Pre-commit configuration file
repos:
  # Use ruff for automatic linting and formatting (configuration is in pyproject.toml)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: [--autofix]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.5
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/hukkin/mdformat
  rev: 0.7.22  # Use the ref you want to point at
  hooks:
  - id: mdformat
    args: [--wrap=120, --number]
    # Optionally add plugins
    additional_dependencies:
    - mdformat-gfm
    - mdformat-ruff
    - mdformat-web
    - mdformat-config
