version: '3.8'
services:
  ap1:
    build: .
    container_name: ap1
    privileged: true
    environment:
    - BASE_SUBNET=2001:db8:abcd:1
    - AP_ID=1
    - NUM_RTS=10
    networks:
      apnet1:
        ipv4_address: 10.1.0.2
        ipv6_address: 2001:db8:abcd:1::fffe
    healthcheck:
      test: curl -g --fail http://[2001:db8:abcd:1::fffe]:8000/which_ip
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
  ap2:
    build: .
    container_name: ap2
    privileged: true
    environment:
    - BASE_SUBNET=2001:db8:abcd:2
    - AP_ID=2
    - NUM_RTS=10
    networks:
      apnet2:
        ipv4_address: 10.2.0.2
        ipv6_address: 2001:db8:abcd:2::fffe
    healthcheck:
      test: curl -g --fail http://[2001:db8:abcd:2::fffe]:8000/which_ip
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 120s
networks:
  apnet1:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
      - subnet: 10.1.0.0/16
      - subnet: 2001:db8:abcd:1::/64
  apnet2:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
      - subnet: 10.2.0.0/16
      - subnet: 2001:db8:abcd:2::/64
